
package vista;

import controladora.Controladora; // Necesario
import javax.swing.JOptionPane; // Necesario para mensajes

public class Registrarse extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registrarse.class.getName());

    private final Controladora control;
    /**
     * Creates new form InicioSesion
     */
    public Registrarse() {
        control = new Controladora();
        initComponents();
        
        jTextField1.setEnabled(false);
        
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // Aquí se llama a tu método
                actualizarCamposPorRol();
            }
        });
        
    }
    
    // Código en Registrarse.java



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recontraseña = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        nombre = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        correo = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        contraseña = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        correo1 = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        correo2 = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(452, 515));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Registrarse");

        jScrollPane1.setViewportView(recontraseña);

        jScrollPane2.setViewportView(nombre);

        jLabel2.setText("Usuario:");

        jLabel3.setText("Repetir Contraseña:");

        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(correo);

        jLabel4.setText("Correo:");

        jScrollPane4.setViewportView(contraseña);

        jLabel5.setText("Contraseña:");

        jLabel6.setText("Teléfono:");

        jScrollPane5.setViewportView(correo1);

        jLabel7.setText("Dirección:");

        jScrollPane6.setViewportView(correo2);

        jLabel8.setText("Rol:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Familia Adoptante", "Voluntario", "Veterinario", "Administrador" }));

        jLabel9.setText("Matricula:");

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addComponent(jLabel2)
                                .addComponent(jScrollPane2)
                                .addComponent(jLabel4)
                                .addComponent(jScrollPane3)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(jScrollPane1)
                                .addComponent(jLabel6)
                                .addComponent(jScrollPane5)
                                .addComponent(jScrollPane6)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnRegistrarse)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarse)
                    .addComponent(jButton1))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
       // Instancia de la Controladora (debe estar declarada en la clase)
    
    
    // --- 1. Captura de Datos de la Vista ---
    String nombreStr = nombre.getText().trim();
    String correoStr = correo.getText().trim();
    String contrasenaStr = contraseña.getText().trim();
    String recontrasenaStr = recontraseña.getText().trim();
    String telefonoStr = correo1.getText().trim(); 
    String direccionStr = correo2.getText().trim(); 
    String matriculaStr = jTextField1.getText().trim();
            
    String rolDisplay = (String) jComboBox1.getSelectedItem(); 
    String rolDB = mapearRol(rolDisplay); // Llama a la función de mapeo

    // --- 2. Validación BÁSICA (Incluyendo Dirección) ---
    if (nombreStr.isEmpty() || correoStr.isEmpty() || contrasenaStr.isEmpty() || 
        telefonoStr.isEmpty() || direccionStr.isEmpty() || rolDB == null) 
    {
        JOptionPane.showMessageDialog(this, "Debe completar todos los campos obligatorios.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    if (!contrasenaStr.equals(recontrasenaStr)) {
        JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // --- 3. Llamada a la Lógica de Negocio ---
    try {
        control.registrarUsuarioPorRol(
            nombreStr, 
            correoStr, 
            contrasenaStr, 
            telefonoStr, 
            direccionStr,
            matriculaStr,
            rolDB);
        
        JOptionPane.showMessageDialog(this, "✅ Usuario (" + rolDisplay + ") registrado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        
        IniciarSesion pantallaInicio = new IniciarSesion(control);
    
    // 2. Hace visible la nueva ventana
    pantallaInicio.setVisible(true);
    
    // 3. (Opcional pero recomendado) Centra la nueva ventana
    pantallaInicio.setLocationRelativeTo(null);
    
    // 4. Cierra la ventana actual de Registro
    this.dispose();
        
        // Limpiar campos
        nombre.setText("");
        correo.setText("");
        contraseña.setText("");
        recontraseña.setText("");
        correo1.setText("");
        correo2.setText("");
        jTextField1.setText("");
        jComboBox1.setSelectedIndex(0);
        
    } catch (modelo.RegistroException e) { 
    // Error de negocio (VALIDO)
    JOptionPane.showMessageDialog(this, e.getMessage(), "Fallo de Registro", JOptionPane.WARNING_MESSAGE);
    
}  catch (NullPointerException e) { 
    // 🟢 Error específico de Bug (ej. 'control' es nulo)
    JOptionPane.showMessageDialog(this, "Error interno de la aplicación (Null).", "Error Crítico", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace(); // Imprime esto para el desarrollador
    
} catch (Exception e) {
    // 🟢 (OPCIONAL) Dejar el "catch-all" al FINAL por si algo se escapó
    JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}
    
    }
    private void actualizarCamposPorRol() {
        // 1. Obtener el valor seleccionado en el JComboBox
        String rolSeleccionado = (String) jComboBox1.getSelectedItem();
        
        // 2. Determinar si el campo debe estar habilitado
        // La variable 'matEnabled' será TRUE solo si el rol es "Veterinario"
        boolean matEnabled = "Veterinario".equals(rolSeleccionado);
        
        // 3. Aplicar la condición al campo de la Matrícula (jTextField1)
        jTextField1.setEnabled(matEnabled);
        
        // 4. Limpieza (Mejora de Usabilidad)
        // Si el campo se deshabilita, borra cualquier texto que tuviera.
        if (!matEnabled) {
            jTextField1.setText(""); 
        }
    }
    
    // 🟢 5. MÉTODO AUXILIAR (Traductor de Roles)
    /**
     * Traduce el rol amigable de la Vista (Display) al código interno (DB).
     * @param rolDisplay El texto del JComboBox (ej. "Familia Adoptante")
     * @return El código del rol (ej. "FAMILIA") o null si no es válido.
     */
    private String mapearRol(String rolDisplay) {
        if (rolDisplay == null || rolDisplay.equals("-")) return null;
        return switch (rolDisplay) {
            case "Familia Adoptante" -> "FAMILIA";
            case "Administrador" -> "ADMINISTRADOR";
            case "Veterinario" -> "VETERINARIO";
            case "Voluntario" -> "VOLUNTARIO";
            default -> null; 
        };
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // Reutilizamos la instancia de controladora ya existente en la clase
            IniciarSesion login = new IniciarSesion(control); 
            
            // Hace visible la ventana de inicio de sesión
            login.setLocationRelativeTo(null);
            login.setVisible(true);
            
            // Cierra la ventana actual de registro
            this.dispose(); 
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al volver a la pantalla de Login: " + e.getMessage(), 
                "Error de Navegación", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JTextPane contraseña;
    private javax.swing.JTextPane correo;
    private javax.swing.JTextPane correo1;
    private javax.swing.JTextPane correo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane nombre;
    private javax.swing.JTextPane recontraseña;
    // End of variables declaration//GEN-END:variables
}
