
package vista;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import controladora.Controladora;
import modelo.Gato; 
import modelo.OperacionException; // ? Importa la excepción de negocio
import modelo.Usuario;

//IMPORT PARA QR
import com.google.zxing.BarcodeFormat;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;

public class VistaFamiliaAdoptante extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaFamiliaAdoptante.class.getName());
    private final Controladora control;
    private final Usuario usuario;
    /**
     * Creates new form VistaAdministrador
     */
    public VistaFamiliaAdoptante(Controladora control, Usuario usuario) {
        this.control = control;
        this.usuario = usuario;
        initComponents();
        
        // Personalizar el saludo
        jLabel1.setText("¡Hola, " + usuario.getNombre() + "!"); //
       
        
        cargarGatosDisponibles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPaneTablaGatosDisponibles = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnVerPerfilGatoSeleccionado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldFiltroNombreGato = new javax.swing.JTextField();
        jTextFieldFiltroNombreRazaGato = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Gatos Disponibles ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("Tabla Gato"); // NOI18N
        jScrollPaneTablaGatosDisponibles.setViewportView(jTable1);

        btnVerPerfilGatoSeleccionado.setText("Ver Perfil de Gato Seleccionado");
        btnVerPerfilGatoSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPerfilGatoSeleccionadoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Raza:");

        jTextFieldFiltroNombreGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFiltroNombreGatoActionPerformed(evt);
            }
        });

        jTextFieldFiltroNombreRazaGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFiltroNombreRazaGatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerPerfilGatoSeleccionado)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPaneTablaGatosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldFiltroNombreGato, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFiltroNombreRazaGato, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFiltroNombreGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFiltroNombreRazaGato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneTablaGatosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerPerfilGatoSeleccionado)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerPerfilGatoSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPerfilGatoSeleccionadoActionPerformed
       try {
       
        int filaSeleccionada = jTable1.getSelectedRow();
        
        // 2. Validación
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un gato de la tabla para ver sus detalles.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        long idGato = (Long) jTable1.getValueAt(filaSeleccionada, 0);
        
        
        Gato gatoCompleto = control.buscarGatoCompleto(idGato);
        
       
        String datosQR = new StringBuilder()
            .append("== Amven Gato ID: ").append(gatoCompleto.getIdGato()).append(" ==\n")
            // ... (resto de la construcción del QR) ...
            .toString();

       
        mostrarQR(datosQR, gatoCompleto.getNombre());

    } catch (OperacionException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Error en la Operación", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        // Mantenemos este catch general, pero el error de casteo ya debería estar resuelto
        JOptionPane.showMessageDialog(this, "Error inesperado al generar QR: " + e.getMessage(), "Error Crítico", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}                                          

// 🟢 MÉTODO AUXILIAR PARA CREAR Y MOSTRAR EL POPUP DEL QR
// (Pega esto al final de tu clase VistaFamiliaAdoptante.java)
private void mostrarQR(String texto, String nombreGato) {
    try {
        // 1. Generar la matriz de bits del QR
        QRCodeWriter qrWriter = new QRCodeWriter();
        BitMatrix bitMatrix = qrWriter.encode(texto, BarcodeFormat.QR_CODE, 300, 300); // Tamaño 300x300
        
        // 2. Convertir la matriz a una imagen
        BufferedImage qrImage = MatrixToImageWriter.toBufferedImage(bitMatrix);
        
        // 3. Crear el PopUp (JDialog)
        JDialog qrDialog = new JDialog(this, "QR para: " + nombreGato, true); // true = modal
        qrDialog.setLayout(new java.awt.FlowLayout());
        
        // 4. Crear el contenedor de la imagen
        JLabel qrLabel = new JLabel(new ImageIcon(qrImage));
        
        // 5. Mostrar
        qrDialog.add(qrLabel);
        qrDialog.pack(); // Ajusta el tamaño de la ventana a la imagen
        qrDialog.setLocationRelativeTo(this); // Centra el popup
        qrDialog.setVisible(true);
        
    } catch (Exception e) {
        // Este catch es para la biblioteca Zxing
        JOptionPane.showMessageDialog(this, "Error al crear la imagen QR.", "Error Zxing", JOptionPane.ERROR_MESSAGE);
    } 
    }//GEN-LAST:event_btnVerPerfilGatoSeleccionadoActionPerformed

    private void jTextFieldFiltroNombreGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFiltroNombreGatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFiltroNombreGatoActionPerformed

    private void jTextFieldFiltroNombreRazaGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFiltroNombreRazaGatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFiltroNombreRazaGatoActionPerformed

    private void cargarGatosDisponibles() {
    try {
        List<Gato> gatos = control.traerGatosDisponibles(); 
        
        DefaultTableModel modeloTabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        // 1. Definir solo las Columnas que quieres mostrar
        String titulos[] = {"ID", "Nombre", "Raza"};
        modeloTabla.setColumnIdentifiers(titulos);
        
        // 2. Llenar la tabla
        if (gatos != null && !gatos.isEmpty()) {
            for (Gato g : gatos) {
                Object[] objeto = {
                    g.getIdGato(), // Lo necesitamos para la lógica
                    g.getNombre(),
                    g.getRaza(),
                };
                modeloTabla.addRow(objeto);
            }
        }
        
        jTable1.setModel(modeloTabla);
        
        // 3. (Opcional) Ocultar la columna ID (Columna 0)
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
        
    } catch (OperacionException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Información", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error inesperado al cargar gatos: " + e.getMessage(), "Error Crítico", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerPerfilGatoSeleccionado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPaneTablaGatosDisponibles;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldFiltroNombreGato;
    private javax.swing.JTextField jTextFieldFiltroNombreRazaGato;
    // End of variables declaration//GEN-END:variables
}
