
package vista;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Controladora;
import modelo.Gato; 
import modelo.OperacionException; // ? Importa la excepción de negocio
import modelo.Usuario;

//IMPORT PARA QR
import com.google.zxing.BarcodeFormat;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;

public class VistaFamiliaAdoptante extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaFamiliaAdoptante.class.getName());
    private final Controladora control;
    private final Usuario usuario;
    /**
     * Creates new form VistaAdministrador
     */
    public VistaFamiliaAdoptante(Controladora control, Usuario usuario) {
        this.control = control;
        this.usuario = usuario;
        initComponents();
        
        // Personalizar el saludo
        jLabel1.setText("¡Hola, " + usuario.getNombre() + "!"); //
       
        
        cargarGatosDisponibles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Gatos Disponibles ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("Tabla Gato"); // NOI18N
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("Postularse");
        jButton1.setName("Postularse"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar");
        jButton2.setName("Actualizar"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Generar QR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(206, 206, 206))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cargarGatosDisponibles();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try {
            // 1. Obtener la fila seleccionada
            int filaSeleccionada = jTable1.getSelectedRow();
            
            // 2. Validación de la Vista: ¿Seleccionó algo?
            if (filaSeleccionada == -1) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un gato de la tabla.", "Error de Postulación", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // 3. Obtener el ID del Gato (Asumimos que está en la Columna 0)
            int idGato = (int) jTable1.getValueAt(filaSeleccionada, 0);
            
            // 4. Obtener el ID de la Familia (del usuario que inició sesión)
            int idFamilia = this.usuario.getIdUsuario(); //
            
            // 5. Llamar a la Controladora (Capa de Negocio)
            control.crearPostulacion(idGato, idFamilia);
            
            // 6. Éxito
            JOptionPane.showMessageDialog(this, "¡Postulación enviada con éxito!", "Postulación Registrada", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (OperacionException e) {
            // Atrapa errores de negocio (ej. "Ya te postulaste a este gato")
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error en la Operación", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Atrapa cualquier otro error (ej. al convertir el ID)
            JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage(), "Error Crítico", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try {
        // 1. Obtener la fila seleccionada
        int filaSeleccionada = jTable1.getSelectedRow();
        
        // 2. Validación
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un gato de la tabla para ver sus detalles.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 3. Obtener el ID del Gato (Oculto en la Columna 0)
        int idGato = (int) jTable1.getValueAt(filaSeleccionada, 0);
        
        // 4. Llamar a la Controladora para traer TODOS los datos
        Gato gatoCompleto = control.buscarGatoCompleto(idGato); // (Crearemos este método)
        
        // 5. Formatear los datos que irán en el QR
        String datosQR = new StringBuilder()
            .append("== Amven Gato ID: ").append(gatoCompleto.getIdGato()).append(" ==\n")
            .append("Nombre: ").append(gatoCompleto.getNombre()).append("\n")
            .append("Raza: ").append(gatoCompleto.getRaza()).append("\n")
            .append("Color: ").append(gatoCompleto.getColor()).append("\n")
            .append("Sexo: ").append(gatoCompleto.getSexo()).append("\n")
           .append("Esterilizado: ").append(gatoCompleto.getEsterilizado().name()).append("\n") //
            .append("Estado Físico: ").append(gatoCompleto.getestadoFisico())
            // (Añade cualquier otro campo que quieras mostrar)
            .toString();

        // 6. Generar y mostrar el QR
        mostrarQR(datosQR, gatoCompleto.getNombre());

    } catch (OperacionException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Error en la Operación", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error inesperado al generar QR: " + e.getMessage(), "Error Crítico", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}                                          

// 🟢 MÉTODO AUXILIAR PARA CREAR Y MOSTRAR EL POPUP DEL QR
// (Pega esto al final de tu clase VistaFamiliaAdoptante.java)
private void mostrarQR(String texto, String nombreGato) {
    try {
        // 1. Generar la matriz de bits del QR
        QRCodeWriter qrWriter = new QRCodeWriter();
        BitMatrix bitMatrix = qrWriter.encode(texto, BarcodeFormat.QR_CODE, 300, 300); // Tamaño 300x300
        
        // 2. Convertir la matriz a una imagen
        BufferedImage qrImage = MatrixToImageWriter.toBufferedImage(bitMatrix);
        
        // 3. Crear el PopUp (JDialog)
        JDialog qrDialog = new JDialog(this, "QR para: " + nombreGato, true); // true = modal
        qrDialog.setLayout(new java.awt.FlowLayout());
        
        // 4. Crear el contenedor de la imagen
        JLabel qrLabel = new JLabel(new ImageIcon(qrImage));
        
        // 5. Mostrar
        qrDialog.add(qrLabel);
        qrDialog.pack(); // Ajusta el tamaño de la ventana a la imagen
        qrDialog.setLocationRelativeTo(this); // Centra el popup
        qrDialog.setVisible(true);
        
    } catch (Exception e) {
        // Este catch es para la biblioteca Zxing
        JOptionPane.showMessageDialog(this, "Error al crear la imagen QR.", "Error Zxing", JOptionPane.ERROR_MESSAGE);
    } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cargarGatosDisponibles() {
    try {
        List<Gato> gatos = control.traerGatosDisponibles(); 
        
        DefaultTableModel modeloTabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        // 1. Definir solo las Columnas que quieres mostrar
        String titulos[] = {"ID", "Nombre", "Raza"};
        modeloTabla.setColumnIdentifiers(titulos);
        
        // 2. Llenar la tabla
        if (gatos != null && !gatos.isEmpty()) {
            for (Gato g : gatos) {
                Object[] objeto = {
                    g.getIdGato(), // Lo necesitamos para la lógica
                    g.getNombre(),
                    g.getRaza(),
                };
                modeloTabla.addRow(objeto);
            }
        }
        
        jTable1.setModel(modeloTabla);
        
        // 3. (Opcional) Ocultar la columna ID (Columna 0)
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
        
    } catch (OperacionException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Información", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error inesperado al cargar gatos: " + e.getMessage(), "Error Crítico", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
